---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  log_level: info

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[deploy_tomcat_war::default]
      - recipe[deploy_tomcat_war::tomcat]
    attributes:
